//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudApi_Implementation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Student_id { get; set; }
        public string student_name { get; set; }
        public string student_email { get; set; }
        public string student_password { get; set; }
        public string student_contact { get; set; }
        public string student_pic { get; set; }
        public int total_enrolment { get; set; }
    }
}
